version: '3'

services:

  # External dependencies
  redis:
    image: redis:alpine
    restart: unless-stopped
    labels:
      - traefik.enable=false
    volumes:
      - "/mnt/ssd-1tb/docker/mailu/redis:/data"
    depends_on:
      - resolver
    dns:
      - 172.26.0.254

  resolver:
    image: ghcr.io/mailu/unbound:${MAILU_VERSION}
    env_file: mailu.env
    restart: unless-stopped
    labels:
      - traefik.enable=false
    networks:
      default:
        ipv4_address: 172.26.0.254

  certdumper:
    image: ghcr.io/mailu/traefik-certdumper:${MAILU_VERSION}
    restart: unless-stopped
    environment:
      - DOMAIN=${DOMAIN}
      - TRAEFIK_VERSION=v2
    volumes:
      - "/mnt/ssd-1tb/docker/traefik/letsencrypt/patz.family:/traefik"
      - "/mnt/ssd-1tb/docker/mailu/certs:/output"
    labels:
      - traefik.enable=false
    dns:
      - 172.26.0.254

  # Core services
  front:
    image: ghcr.io/mailu/nginx:${MAILU_VERSION}
    restart: unless-stopped
    env_file: ../stack.env
    logging:
      driver: json-file
    ports:
      - "25:25"
      - "110:110"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
      - "995:995"
    volumes:
      - "/mnt/ssd-1tb/docker/mailu/certs:/certs"
      - "/mnt/ssd-1tb/docker/mailu/overrides/nginx:/overrides:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mailu-front.rule=Host(`mail.${DOMAIN}`) || Host(`mail.patz.app`) || Host(`mail.whynot.holdings`)"
      - "traefik.http.routers.mailu-front.entrypoints=websecure"
      - "traefik.http.routers.mailu-front.tls.certresolver=${DOMAIN}"
      - "traefik.http.routers.mailu-front.tls.domains[0].main=${DOMAIN}"
      - "traefik.http.routers.mailu-front.tls.domains[0].sans=mail.${DOMAIN},smtp.${DOMAIN},imap.${DOMAIN}"
      - "traefik.http.routers.mailu-front.tls.domains[1].main=patz.app"
      - "traefik.http.routers.mailu-front.tls.domains[1].sans=mail.patz.app,smtp.patz.app,imap.patz.app"
      - "traefik.http.routers.mailu-front.tls.domains[2].main=whynot.holdings"
      - "traefik.http.routers.mailu-front.tls.domains[2].sans=mail.whynot.holdings,smtp.whynot.holdings,imap.whynot.holdings"
      - "traefik.http.routers.mailu-front.service=mailu-front"
      - "traefik.http.services.mailu-front.loadbalancer.server.port=80"

    depends_on:
      - certdumper
      - resolver
    networks:
      - default
      - traefik
      - webmail
    dns:
      - 172.26.0.254

  admin:
    image: ghcr.io/mailu/admin:${MAILU_VERSION}
    restart: unless-stopped
    env_file: ../stack.env
    labels:
      - traefik.enable=false
    volumes:
      - "/mnt/ssd-1tb/docker/mailu/data:/data"
      - "/mnt/ssd-1tb/docker/mailu/dkim:/dkim"
    depends_on:
      - redis
      - resolver
    dns:
      - 172.26.0.254

  imap:
    image: ghcr.io/mailu/dovecot:${MAILU_VERSION}
    restart: unless-stopped
    env_file: ../stack.env
    labels:
      - traefik.enable=false
    volumes:
      - "/mnt/ssd-1tb/docker/mailu/mail:/mail"
      - "/mnt/ssd-1tb/docker/mailu/overrides/dovecot:/overrides:ro"
    depends_on:
      - front
      - resolver
    networks:
      - default
    dns:
      - 172.26.0.254

  smtp:
    image: ghcr.io/mailu/postfix:${MAILU_VERSION}
    restart: unless-stopped
    env_file: ../stack.env
    labels:
      - traefik.enable=false
    volumes:
      - "/mnt/ssd-1tb/docker/mailu/mailqueue:/queue"
      - "/mnt/ssd-1tb/docker/mailu/overrides/postfix:/overrides:ro"
    networks:
      - default
    depends_on:
      - front
      - resolver
    dns:
      - 172.26.0.254

  oletools:
    image: ghcr.io/mailu/oletools:${MAILU_VERSION}
    hostname: oletools
    restart: unless-stopped
    labels:
      - traefik.enable=false
    networks:
      - noinet
    depends_on:
      - resolver
    dns:
      - 172.26.0.254

  antispam:
    image: ghcr.io/mailu/rspamd:${MAILU_VERSION}
    hostname: antispam
    restart: unless-stopped
    env_file: ../stack.env
    labels:
      - traefik.enable=false
    volumes:
      - "/mnt/ssd-1tb/docker/mailu/filter:/var/lib/rspamd"
      - "/mnt/ssd-1tb/docker/mailu/overrides/rspamd:/etc/rspamd/override.d"
    networks:
      - default
      - noinet
    depends_on:
      - front
      - redis
      - oletools
      - resolver
    dns:
      - 172.26.0.254

  webmail:
    image: ghcr.io/mailu/webmail:${MAILU_VERSION}
    restart: unless-stopped
    env_file: ../stack.env
    labels:
      - traefik.enable=false
    networks:
      - webmail
    volumes:
      - "/mnt/ssd-1tb/docker/mailu/webmail:/data"
      - "/mnt/ssd-1tb/docker/mailu/overrides/roundcube:/overrides:ro"
    depends_on:
      - front
    dns:
      - 172.26.0.254

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.26.0.0/24
  webmail:
    driver: bridge
  noinet:
    driver: bridge
    internal: true
  traefik:
    name: traefik
    external: true
