version: '3'

services:

  # External dependencies
  redis:
    image: redis:alpine
    restart: always
    labels:
      - traefik.enable=false
    volumes:
      - "/mnt/ssd-1tb/docker/mailu/redis:/data"

  certdumper:
    image: mailu/traefik-certdumper:${MAILU_VERSION}
    restart: always
    environment:
      - DOMAIN=${DOMAIN}
      - TRAEFIK_VERSION=v2
    volumes:
      - "/mnt/ssd-1tb/docker/traefik/letsencrypt/patz.family:/traefik"
      - "/mnt/ssd-1tb/docker/mailu/certs:/output"
    labels:
      - traefik.enable=false

  # Core services
  front:
    image: mailu/nginx:${MAILU_VERSION}
    restart: always
    env_file:
      - .env
    logging:
      driver: json-file
    ports:
      - "25:25"
      - "110:110"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
      - "995:995"
    volumes:
      - "/mnt/ssd-1tb/docker/mailu/certs:/certs"
      - "/mnt/ssd-1tb/docker/mailu/overrides/nginx:/overrides:ro"
    labels:
      - traefik.enable=true
      - traefik.http.services.mailu-front.loadbalancer.server.port=80

      - traefik.http.routers.mailu-front-patz-app.rule=Host(`mail.patz.app`)
      - traefik.http.routers.mailu-front-patz-app.entrypoints=websecure
      - traefik.http.routers.mailu-front-patz-app.tls.certresolver=patz.app
      - traefik.http.routers.mailu-front-patz-app.tls.domains[0].main=patz.app
      - traefik.http.routers.mailu-front-patz-app.tls.domains[0].sans=mail.patz.app,smtp.patz.app
      - traefik.http.routers.mailu-front-patz-app.service=mailu-front

      - traefik.http.routers.mailu-front-patz-family.rule=Host(`mail.${DOMAIN}`)
      - traefik.http.routers.mailu-front-patz-family.entrypoints=websecure
      - traefik.http.routers.mailu-front-patz-family.tls.certresolver=${DOMAIN}
      - traefik.http.routers.mailu-front-patz-family.tls.domains[0].main=${DOMAIN}
      - traefik.http.routers.mailu-front-patz-family.tls.domains[0].sans=mail.${DOMAIN},smtp.${DOMAIN}
      - traefik.http.routers.mailu-front-patz-family.service=mailu-front

    depends_on:
      - certdumper
    networks:
      - default
      - traefik

  admin:
    image: mailu/admin:${MAILU_VERSION}
    restart: always
    env_file:
      - .env
    labels:
      - traefik.enable=false
    volumes:
      - "/mnt/ssd-1tb/docker/mailu/data:/data"
      - "/mnt/ssd-1tb/docker/mailu/dkim:/dkim"
    depends_on:
      - redis

  imap:
    image: mailu/dovecot:${MAILU_VERSION}
    restart: always
    env_file:
      - .env
    labels:
      - traefik.enable=false
    volumes:
      - "/mnt/ssd-1tb/docker/mailu/mail:/mail"
      - "/mnt/ssd-1tb/docker/mailu/overrides/dovecot:/overrides:ro"
    depends_on:
      - front
    networks:
      - default

  smtp:
    image: mailu/postfix:${MAILU_VERSION}
    restart: always
    env_file:
      - .env
      - secrets.env
    labels:
      - traefik.enable=false
    volumes:
      - "/mnt/ssd-1tb/docker/mailu/mailqueue:/queue"
      - "/mnt/ssd-1tb/docker/mailu/overrides/postfix:/overrides:ro"
    networks:
      - default
    depends_on:
      - front

  antispam:
    image: mailu/rspamd:${MAILU_VERSION}
    hostname: antispam
    restart: always
    env_file:
      - .env
    labels:
      - traefik.enable=false
    volumes:
      - "/mnt/ssd-1tb/docker/mailu/filter:/var/lib/rspamd"
      - "/mnt/ssd-1tb/docker/mailu/overrides/rspamd:/etc/rspamd/override.d:ro"
    networks:
      - default
    depends_on:
      - front

  webmail:
    image: mailu/roundcube:${MAILU_VERSION}
    restart: always
    env_file:
      - .env
    labels:
      - traefik.enable=false
    networks:
      - default
    volumes:
      - "/mnt/ssd-1tb/docker/mailu/webmail:/data"
      - "/mnt/ssd-1tb/docker/mailu/overrides/roundcube:/overrides:ro"
    depends_on:
      - imap

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.26.0.0/24
  traefik:
    external:
      name: traefik
