version: "3.3"

networks:
  auth_internal:
    external: true
  traefik:
    external:
      name: traefik

services:
  code_server:
    image: lscr.io/linuxserver/code-server:4.6.0
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=Europe/Berlin
    volumes:
      - ${HOME}:/config
    ports:
      - 8443
    networks:
      - auth_internal
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.vs-code.rule=Host(`code.patz.app`)
      - traefik.http.routers.vs-code.entrypoints=websecure
      - traefik.http.routers.vs-code.tls.certresolver=patz.app
      - traefik.http.routers.vs-code.tls.domains[0].main=patz.app
      - traefik.http.routers.vs-code.tls.domains[0].sans=code.patz.app
      - traefik.http.routers.vs-code.middlewares=keycloak@file
      - traefik.http.services.vs-code.loadbalancer.server.port=8443
    restart: always
