services:
  document:
    image: onlyoffice/documentserver:${ONLYOFFICE_TAG:-7.2.0}
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      JWT_ENABLED: "true"
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - traefik
    volumes:
      - data:/var/www/onlyoffice/Data
      - db:/var/lib/postgresql
      - fonts:/usr/share/fonts/truetype/custom
      - lib:/var/lib/onlyoffice
      - logs:/var/log/onlyoffice
      - rabbitmq:/var/lib/rabbitmq
      - redis:/var/lib/redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.onlyoffice-ds-websecure.entrypoints=websecure"
      - "traefik.http.routers.onlyoffice-ds-websecure.rule=Host(`office.patz.app`)"
      - "traefik.http.routers.onlyoffice-ds-websecure.middlewares=security-headers@file,onlyoffice-ds-header"
      - "traefik.http.routers.onlyoffice-ds-websecure.tls=true"
      - "traefik.http.routers.onlyoffice-ds-websecure.tls.certresolver=patz.app"
      - "traefik.http.routers.onlyoffice-ds-websecure.tls.domains[0].main=patz.app"
      - "traefik.http.routers.onlyoffice-ds-websecure.tls.domains[0].sans=office.patz.app"
      - "traefik.http.services.onlyoffice-ds.loadbalancer.server.port=80"
      - "traefik.http.middlewares.onlyoffice-ds-header.headers.referrerPolicy=no-referrer"

volumes:
  data:
  db:
  fonts:
  lib:
  logs:
  rabbitmq:
  redis:

networks:
  traefik:
    name: traefik
    external: true
