networks:

  traefik:
    name: traefik
    external: true


services:

  storagenode:
    image: storjlabs/storagenode:latest
    restart: unless-stopped
    stop_grace_period: 300s
    ports:
      - "${PORT}:28967/tcp"
      - "${PORT}:28967/udp"
    networks:
      - traefik
    env_file:
      - ../../stack.env
    environment:
      - AUTO_UPDATE=true
      - ADDRESS=storj.patz.app:${PORT}
      - EMAIL=martin@patz.family
    user: "${UID:-0}:${GID:-0}"
    volumes:
      - ${DATA_ROOT}/identity:/app/identity
      - ${DATA_ROOT}/config:/app/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.${NODE}.entrypoints=websecure
      - traefik.http.routers.${NODE}.rule=Host(`${NODE}.storj.patz.app`)
      - traefik.http.routers.${NODE}.tls.certresolver=patz.app
      - traefik.http.routers.${NODE}.middlewares=keycloak@file
      - traefik.http.services.${NODE}.loadbalancer.server.port=14002
