version: '3'

networks:
  auth_internal:
    external: true
  traefik:
    name: traefik

services:
  openldap:
    image: osixia/openldap
    hostname: openldap
    environment:
      - LDAP_DOMAIN=patz.app
      - LDAP_ORGANISATION=Family Patz
      - LDAP_TLS=false
    networks:
      - auth_internal
      - traefik
    volumes:
      - /mnt/ssd-1tb/docker/auth/openldap/db:/var/lib/ldap
      - /mnt/ssd-1tb/docker/auth/openldap/config:/etc/ldap/slapd.d
    labels:
      - traefik.enable=false
    restart: unless-stopped

  lam:
    image: jacksgt/ldap-account-manager
    networks:
      - auth_internal
      - traefik
    depends_on:
      - openldap
    volumes:
      - ./lam/config.cfg:/var/www/html/config/config.cfg
      - ./lam/patz.conf:/var/www/html/config/patz.conf
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.auth-lam.entrypoints=websecure
      - traefik.http.routers.auth-lam.rule=Host(`iam.patz.app`)
      - traefik.http.routers.auth-lam.tls=true
      - traefik.http.routers.auth-lam.tls.certresolver=patz.app
      - traefik.http.routers.auth-lam.tls.domains[0].main=patz.app
      - traefik.http.routers.auth-lam.tls.domains[0].sans=iam.patz.app
      - traefik.http.services.auth-lam.loadbalancer.server.port=8080
      - traefik.http.routers.auth-lam.middlewares=keycloak@file
    restart: unless-stopped

  keycloak-db:
    image: postgres:10.1
    volumes:
      - /mnt/ssd-1tb/docker/auth/keycloak/db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    env_file: keycloak.env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - auth_internal
    labels:
      - traefik.enable=false
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:16.1.1
    # command: start --proxy edge --hostname-strict=false
    depends_on:
      - keycloak-db
    env_file: keycloak.env
    environment:
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - DB_PASSWORD=${DB_PASSWORD}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - auth_internal
      - traefik
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.auth-keycloak.entrypoints=websecure
      - traefik.http.routers.auth-keycloak.rule=Host(`keycloak.patz.app`)
      - traefik.http.routers.auth-keycloak.tls=true
      - traefik.http.routers.auth-keycloak.tls.certresolver=patz.app
      - traefik.http.routers.auth-keycloak.tls.domains[0].main=patz.app
      - traefik.http.routers.auth-keycloak.tls.domains[0].sans=keycloak.patz.app
      - traefik.http.services.auth-keycloak.loadbalancer.server.port=8080
    restart: unless-stopped
