version: '3'

services:
  plex:
    image: plexinc/pms-docker:plexpass
    container_name: plex
    restart: unless-stopped
    hostname: tatooine
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    volumes:
      - ${MOUNT_CONFIG}:/config
      - transcode:/transcode
      - /share/Audiobooks:/data/audiobooks
      - /share/Plex:/data/plex
      - /share/Movies:/data/movies
      - /share/Music:/data/music
      - /share/Series:/data/tv-shows
    env_file:
      - secrets.env

  backup:
    image: blacklabelops/volumerize
    restart: unless-stopped
    volumes:
      - backup_cache:/volumerize-cache
      - ${MOUNT_CONFIG}:/source
      - /share/Backup/docker/volumes/plex:/backup
    environment:
      - TZ=Europe/Berlin
      - VOLUMERIZE_SOURCE=/source
      - VOLUMERIZE_TARGET=file:///backup

volumes:
  transcode:
  backup_cache:

