networks:
  traefik:
    name: traefik
    external: true

volumes:
  transcode:

services:
  plex:
    image: plexinc/pms-docker:plexpass
    restart: unless-stopped
    networks:
      - traefik
    ports:
      - 32400:32400/tcp
    volumes:
      - transcode:/transcode
      - /mnt/ssd-1tb/docker/plex/config:/config
      - /mnt/hdd-16tb/media/audiobooks:/data/audiobooks
      - /mnt/hdd-16tb/media/plex:/data/plex
      - /mnt/hdd-16tb/media/movies:/data/movies
      - /mnt/hdd-16tb/media/music:/data/music
      - /mnt/hdd-16tb/media/tv-shows:/data/tv-shows
    environment:
      ADVERTISE_IP: http://arnold.local:32400/,https://plex.patz.app:443
      PLEX_UID: 1001
      PLEX_GID: 1002
      TZ: Europe/Berlin
      PLEX_CLAIM: ${PLEX_CLAIM}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plex.entrypoints=websecure"
      - "traefik.http.routers.plex.rule=Host(`plex.patz.app`)"
      - "traefik.http.routers.plex.tls=true"
      - "traefik.http.routers.plex.tls.certresolver=patz.app"
      - "traefik.http.routers.plex.tls.domains[0].main=patz.app"
      - "traefik.http.routers.plex.tls.domains[0].sans=plex.patz.app"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"

