version: '3'

volumes:
  transcode:

services:
  plex:
    image: plexinc/pms-docker:plexpass
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
    volumes:
      - transcode:/transcode
      - /mnt/ssd-1tb/docker/plex/config:/config
      - /mnt/hdd-16tb/media/audiobooks:/data/audiobooks
      - /mnt/hdd-16tb/media/plex:/data/plex
      - /mnt/hdd-16tb/media/movies:/data/movies
      - /mnt/hdd-16tb/media/music:/data/music
      - /mnt/hdd-16tb/media/tv-shows:/data/tv-shows
    labels:
      - traefik.enable=false
    environment:
      ADVERTISE_IP: http://arnold.local:32400/
      PLEX_UID: 1001
      PLEX_GID: 1002
      TZ: Europe/Berlin
      PLEX_CLAIM: ${PLEX_CLAIM}
