version: '3'

services:
  plex:
    image: plexinc/pms-docker:plexpass
    container_name: plex
    restart: always
    hostname: tatooine
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    volumes:
      - transcode:/transcode
      - ${MOUNT_CONFIG}:/config
      - ${MOUNT_DATA}/audiobooks:/data/audiobooks
      - ${MOUNT_DATA}/plex:/data/plex
      - ${MOUNT_DATA}/movies:/data/movies
      - ${MOUNT_DATA}/music:/data/music
      - ${MOUNT_DATA}/tv-shows:/data/tv-shows
    labels:
      - traefik.enable=false
    env_file:
      - .env
      - /mnt/ssd-1tb/docker/plex/secrets.env

volumes:
  transcode:

