version: "2.1"

networks:
  default:
  auth_internal:
    external: true
  traefik:
    external:
      name: traefik

services:
  piwigo_db:
    image: mariadb:10.7
    restart: always
    privileged: true
    volumes:
      - /mnt/ssd-1tb/docker/piwigo/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: piwigodb
      MYSQL_USER: piwigo
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: supersecurepassword
    networks:
      - default

  piwigo:
    image: lscr.io/linuxserver/piwigo:12.2.0
    container_name: piwigo
    environment:
      - PUID=1001
      - PGID=1002
      - TZ=Europe/Berlin
    volumes:
      - /mnt/ssd-1tb/docker/piwigo/config:/config
      - /mnt/hdd-16tb/docker/piwigo/gallery:/gallery
    ports:
      - 80
    networks:
      - auth_internal
      - default
      - traefik
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.piwigo.entrypoints=websecure"
      - "traefik.http.routers.piwigo.rule=Host(`pictures.patz.app`)"
      - "traefik.http.routers.piwigo.tls=true"
      - "traefik.http.routers.piwigo.tls.certresolver=patz.app"
      - "traefik.http.routers.piwigo.tls.domains[0].main=patz.app"
      - "traefik.http.routers.piwigo.tls.domains[0].sans=pictures.patz.app"
      - "traefik.http.services.piwigo.loadbalancer.server.port=80"
