version: "3.2"

services:
  guacd:
    image: guacamole/guacd
    networks:
      - guacamole
    restart: always

  postgres:
    image: postgres
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: ChooseYourOwnPasswordHere1234
      POSTGRES_USER: guacamole_user
    networks:
      guacamole:
        aliases:
          - guacamole_postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
      - ${PWD}/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql:ro

  guacamole:
    image: guacamole/guacamole
    depends_on:
      - guacd
      - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: guacamole_postgres
      POSTGRES_PASSWORD: ChooseYourOwnPasswordHere1234
      POSTGRES_USER: guacamole_user
    labels:
      - "traefik.enable=true"
      - "traefik.backend=guacamole"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:ptatooine.myqnapcloud.com;PathPrefix:/guacamole"
    networks:
      - guacamole
      - traefik
    ports:
      - 8080/tcp
    restart: always

volumes:
  db:

networks:
  traefik:
    external:
      name: traefik_default
  guacamole:
