version: "3.3"

services:

  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - "traefik:/tmp"
      - "./letsencrypt:/letsencrypt"
      - "./traefik.yml:/etc/traefik/traefik.yml"
      - "./dynamic:/etc/traefik/dynamic"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: "containous/whoami"
    container_name: "whoami"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami-web.entrypoints=web"
      - "traefik.http.routers.whoami-web.rule=Host(`whoami.patz.app`)"
      - "traefik.http.routers.whoami-web.middlewares=redirect-https@file"
      - "traefik.http.routers.whoami-websecure.entrypoints=websecure"
      - "traefik.http.routers.whoami-websecure.rule=Host(`whoami.patz.app`)"
      - "traefik.http.routers.whoami-websecure.tls=true"
      - "traefik.http.routers.whoami-websecure.tls.certresolver=patz.app"
      - "traefik.http.routers.whoami-websecure.tls.domains[0].main=patz.app"
      - "traefik.http.routers.whoami-websecure.tls.domains[0].sans=whoami.patz.app"

volumes:
  traefik:

