version: "3.3"

services:
  traefik:
    image: "traefik:v2.5.2"
    container_name: "traefik"
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - "traefik:/tmp"
      - "./letsencrypt:/letsencrypt"
      - "./traefik.yml:/etc/traefik/traefik.yml"
      - "./dynamic:/etc/traefik/dynamic"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefik

  forward-auth:
    image: thomseddon/traefik-forward-auth:2.2
    environment:
      - DEFAULT_PROVIDER=oidc
      - PROVIDERS_OIDC_CLIENT_ID=traefik-forward-auth
      - PROVIDERS_OIDC_CLIENT_SECRET=5v5C4sHLU5XtZcE34yMTX73W3XdhprpH
      - PROVIDERS_OIDC_ISSUER_URL=https://keycloak.patz.app/auth/realms/patz
      - SECRET=LH49wCZ4ZijgUTfm8etb
      - AUTH_HOST=auth.patz.app
      - COOKIE_DOMAIN=patz.app
      - INSECURE_COOKIE=false
      - LOG_LEVEL=debug
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.forward-auth.entrypoints=websecure
      - traefik.http.routers.forward-auth.rule=Host(`auth.patz.app`)
      - traefik.http.routers.forward-auth.tls=true
      - traefik.http.routers.forward-auth.tls.certresolver=patz.app
      - traefik.http.routers.forward-auth.tls.domains[0].main=patz.app
      - traefik.http.routers.forward-auth.tls.domains[0].sans=auth.patz.app
      - traefik.http.routers.forward-auth.middlewares=keycloak@file
      - traefik.http.services.forward-auth.loadbalancer.server.port=4181
    restart: always

  whoami:
    image: "containous/whoami"
    container_name: "whoami"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami-web.entrypoints=web"
      - "traefik.http.routers.whoami-web.rule=Host(`whoami.patz.app`)"
      - "traefik.http.routers.whoami-web.middlewares=redirect-https@file"
      - "traefik.http.routers.whoami-websecure.entrypoints=websecure"
      - "traefik.http.routers.whoami-websecure.rule=Host(`whoami.patz.app`)"
      - "traefik.http.routers.whoami-websecure.tls=true"
      - "traefik.http.routers.whoami-websecure.tls.certresolver=patz.app"
      - "traefik.http.routers.whoami-websecure.tls.domains[0].main=patz.app"
      - "traefik.http.routers.whoami-websecure.tls.domains[0].sans=whoami.patz.app"
    networks:
      - traefik

volumes:
  traefik:

networks:
  traefik:
    external:
      name: traefik
