global:
  sendAnonymousUsage: true

log:
  level: WARN

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    network: traefik
    watch: true
    endpoint: unix:///var/run/docker.sock
  file:
    directory: /etc/traefik/dynamic

certificatesResolvers:
  patz.app:
    acme:
      email: postmaster@martin-patz.de
      storage: letsencrypt/patz.app/acme.json
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      tlsChallenge: {}
      httpChallenge:
        entrypoint: web
  patz.family:
    acme:
      email: postmaster@martin-patz.de
      storage: letsencrypt/patz.family/acme.json
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      tlsChallenge: {}
      httpChallenge:
        entrypoint: web

api:
  dashboard: true
