global:
  sendAnonymousUsage: true

log:
  level: WARN

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

  # Mailu EntryPoints
  smtp:
    address: ":25"
  smtps:
    address: ":465"
  submission:
    address: ":587"
  pop3:
    address: ":110"
  pop3s:
    address: ":995"
  imap:
    address: ":143"
  imaps:
    address: ":993"


providers:
  docker:
    network: traefik
    watch: true
    exposedByDefault: false
    endpoint: unix:///var/run/docker.sock
  file:
    directory: /etc/traefik/dynamic

certificatesResolvers:
  patz.app:
    acme:
      email: postmaster@martin-patz.de
      storage: letsencrypt/patz.app/acme.json
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      tlsChallenge: {}
      httpChallenge:
        entrypoint: web
  patz.family:
    acme:
      email: postmaster@martin-patz.de
      storage: letsencrypt/patz.family/acme.json
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      tlsChallenge: {}
      httpChallenge:
        entrypoint: web
  bergaufboardab.de:
    acme:
      email: postmaster@martin-patz.de
      storage: letsencrypt/bergaufboardab.de/acme.json
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      tlsChallenge: {}
      httpChallenge:
        entrypoint: web
  whynot.holdings:
    acme:
      email: postmaster@martin-patz.de
      storage: letsencrypt/whynot.holdings/acme.json
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      tlsChallenge: {}
      httpChallenge:
        entrypoint: web

api:
  dashboard: true
