version: "3.3"

services:
  db:
    image: mariadb:10.2
    volumes:
      - ${MOUNT_DB}:/var/lib/mysql
    networks:
      - traefik
    env_file: ../stack.env
    labels:
      - traefik.enable=false
    restart: always

  redis:
    image: redis:4.0-alpine
    volumes:
      - redis:/data
    networks:
      - traefik
    labels:
      - traefik.enable=false
    restart: always

  nextcloud:
    image: crazymax/nextcloud:${NEXTCLOUD_TAG}
    depends_on:
      - db
      - redis
    volumes:
      - ${MOUNT_DATA}:/data
      - ${MOUNT_MEDIA}/audiobooks:/external/audiobooks:ro
      - ${MOUNT_MEDIA}/plex:/external/plex:ro
      - ${MOUNT_MEDIA}/movies:/external/movies:ro
      - ${MOUNT_MEDIA}/music:/external/music:ro
      - ${MOUNT_MEDIA}/tv-shows:/external/tv-shows:ro
    networks:
      - traefik
    env_file: ../stack.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.patz-nc-websecure.entrypoints=websecure"
      - "traefik.http.routers.patz-nc-websecure.rule=Host(`cloud.patz.app`)"
      - "traefik.http.routers.patz-nc-websecure.middlewares=nc-redirect,ssl-header@file"
      - "traefik.http.routers.patz-nc-websecure.tls=true"
      - "traefik.http.routers.patz-nc-websecure.tls.certresolver=patz.app"
      - "traefik.http.routers.patz-nc-websecure.tls.domains[0].main=patz.app"
      - "traefik.http.routers.patz-nc-websecure.tls.domains[0].sans=cloud.patz.app"
      - "traefik.http.services.nc.loadbalancer.server.port=8000"
      - "traefik.http.middlewares.nc-redirect.redirectregex.permanent=true"
      - "traefik.http.middlewares.nc-redirect.redirectregex.regex=https://(.*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.nc-redirect.redirectregex.replacement=https://$${1}/remote.php/dav/"
      - "traefik.http.middlewares.nc-header.headers.referrerPolicy=no-referrer"
      - "traefik.http.middlewares.nc-header.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.nc-header.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.nc-header.headers.stsPreload=true"
      - "traefik.http.middlewares.nc-header.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.nc-header.headers.browserXssFilter=true"
    restart: always

  cron:
    image: crazymax/nextcloud:${NEXTCLOUD_TAG}
    depends_on:
      - nextcloud
    volumes:
      - ${MOUNT_DATA}:/data
    networks:
      - traefik
    env_file: ../stack.env
    environment:
      - "SIDECAR_CRON=1"
      - "CRON_PERIOD=*/15 * * * *"
    labels:
      - traefik.enable=false
    restart: always

volumes:
  redis:

networks:
  traefik:
    external:
      name: traefik

