version: "3.3"

services:
  db:
    image: mariadb:10.2
    hostname: nextcloud_db
    volumes:
      - ${MOUNT_DB}:/var/lib/mysql
    networks:
      - traefik
    env_file:
      - .env
      - secrets.env
    restart: always

  redis:
    image: redis:4.0-alpine
    container_name: nextcloud_redis
    volumes:
      - redis:/data
    networks:
      - traefik
    restart: always

  nextcloud:
    image: crazymax/nextcloud:${NEXTCLOUD_TAG}
    container_name: nextcloud
    depends_on:
      - db
      - redis
    volumes:
      - ${MOUNT_DATA}:/data
    networks:
      - traefik
    env_file:
      - .env
      - secrets.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.patz-nc-web.entrypoints=web"
      - "traefik.http.routers.patz-nc-web.rule=Host(`cloud.patz.app`)"
      - "traefik.http.routers.patz-nc-web.middlewares=redirect-https@file"
      - "traefik.http.routers.patz-nc-websecure.entrypoints=websecure"
      - "traefik.http.routers.patz-nc-websecure.rule=Host(`cloud.patz.app`)"
      - "traefik.http.routers.patz-nc-websecure.middlewares=nc-redirect"
      - "traefik.http.routers.patz-nc-websecure.tls=true"
      - "traefik.http.routers.patz-nc-websecure.tls.certresolver=patz.app"
      - "traefik.http.routers.patz-nc-websecure.tls.domains[0].main=patz.app"
      - "traefik.http.routers.patz-nc-websecure.tls.domains[0].sans=cloud.patz.app"
      - "traefik.http.routers.qnap-nc-web.entrypoints=web"
      - "traefik.http.routers.qnap-nc-web.rule=Host(`ptatooine.myqnapcloud.com`)"
      - "traefik.http.routers.qnap-nc-web.middlewares=redirect-https@file"
      - "traefik.http.routers.qnap-nc-websecure.entrypoints=websecure"
      - "traefik.http.routers.qnap-nc-websecure.rule=Host(`ptatooine.myqnapcloud.com`)"
      - "traefik.http.routers.qnap-nc-websecure.middlewares=nc-redirect,nc-header"
      - "traefik.http.routers.qnap-nc-websecure.tls=true"
      - "traefik.http.routers.qnap-nc-websecure.tls.certresolver=ptatooine.myqnapcloud.com"
      - "traefik.http.routers.qnap-nc-websecure.tls.domains[1].main=ptatooine.myqnapcloud.com"
      - "traefik.http.routers.qnap-nc-websecure.tls.domains[1].sans=ptatooine.myqnapcloud.com"
      - "traefik.http.services.nc.loadbalancer.server.port=8000"
      - "traefik.http.middlewares.nc-redirect.redirectregex.permanent=true"
      - "traefik.http.middlewares.nc-redirect.redirectregex.regex=https://(.*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.nc-redirect.redirectregex.replacement=https://$${1}/remote.php/dav/"
      - "traefik.http.middlewares.nc-header.headers.referrerPolicy=no-referrer"
      - "traefik.http.middlewares.nc-header.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.nc-header.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.nc-header.headers.stsPreload=true"
      - "traefik.http.middlewares.nc-header.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.nc-header.headers.browserXssFilter=true"
      - "traefik.http.middlewares.nc-header.headers.customRequestHeaders.X-Forwarded-Proto=https"
    restart: always

  cron:
    image: crazymax/nextcloud:${NEXTCLOUD_TAG}
    container_name: nextcloud_cron
    depends_on:
      - nextcloud
    volumes:
      - ${MOUNT_DATA}:/data
    networks:
      - traefik
    env_file:
      - .env
      - secrets.env
    environment:
      - "SIDECAR_CRON=1"
      - "CRON_PERIOD=*/15 * * * *"
    restart: always

volumes:
  redis:

networks:
  traefik:
    external:
      name: traefik
