version: "3.3"

volumes:
  redis:

networks:
  traefik:
    name: traefik
    external: true

services:
  db:
    image: mariadb:10.2
    restart: unless-stopped
    volumes:
      - ${MOUNT_DB}:/var/lib/mysql
    networks:
      - traefik
    env_file: ../stack.env
    labels:
      - traefik.enable=false

  redis:
    image: redis:4.0-alpine
    restart: unless-stopped
    volumes:
      - redis:/data
    networks:
      - traefik
    labels:
      - traefik.enable=false

  nextcloud:
    image: crazymax/nextcloud:${NEXTCLOUD_TAG:-24.0.5}
    restart: unless-stopped
    depends_on:
      - db
      - redis
    volumes:
      - ${MOUNT_DATA}:/data
    networks:
      - traefik
    env_file: ../stack.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.patz-nc-websecure.entrypoints=websecure"
      - "traefik.http.routers.patz-nc-websecure.rule=Host(`cloud.patz.app`)"
      - "traefik.http.routers.patz-nc-websecure.middlewares=nc-dav-redirect,nc-rest-redirect,nc-no-index,ssl-header@file"
      - "traefik.http.routers.patz-nc-websecure.tls=true"
      - "traefik.http.routers.patz-nc-websecure.tls.certresolver=patz.app"
      - "traefik.http.routers.patz-nc-websecure.tls.domains[0].main=patz.app"
      - "traefik.http.routers.patz-nc-websecure.tls.domains[0].sans=cloud.patz.app"
      - "traefik.http.services.nc.loadbalancer.server.port=8000"

      - "traefik.http.middlewares.nc-dav-redirect.redirectregex.permanent=true"
      - "traefik.http.middlewares.nc-dav-redirect.redirectregex.regex=^/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.nc-dav-redirect.redirectregex.replacement=/remote.php/dav/"

      - "traefik.http.middlewares.nc-rest-redirect.redirectregex.permanent=true"
      - "traefik.http.middlewares.nc-rest-redirect.redirectregex.regex=^(/.well-known.*)"
      - "traefik.http.middlewares.nc-rest-redirect.redirectregex.replacement=/index.php$$1"

      - "traefik.http.middlewares.nc-no-index.headers.customResponseHeaders.X-Robots-Tag=noindex,nofollow"

  cron:
    image: crazymax/nextcloud:${NEXTCLOUD_TAG}
    restart: unless-stopped
    depends_on:
      - nextcloud
    volumes:
      - ${MOUNT_DATA}:/data
    networks:
      - traefik
    env_file: ../stack.env
    environment:
      - "SIDECAR_CRON=1"
      - "CRON_PERIOD=*/15 * * * *"
    labels:
      - traefik.enable=false
  
  preview_generator:
    image: crazymax/nextcloud:${NEXTCLOUD_TAG}
    restart: unless-stopped
    depends_on:
      - nextcloud
    volumes:
      - ${MOUNT_DATA}:/data
    networks:
      - traefik
    env_file: ../stack.env
    environment:
      - "SIDECAR_PREVIEWGEN=1"
      - "PREVIEWGEN_PERIOD=0 * * * *"
    labels:
      - traefik.enable=false
