version: "3.2"

services:
  db:
    image: mariadb:10.2
    hostname: nextcloud_db
    volumes:
      - ${MOUNT_DB}:/var/lib/mysql
    networks:
      - traefik
    env_file:
      - secrets.env
    restart: always

  redis:
    image: redis:4.0-alpine
    container_name: nextcloud_redis
    volumes:
      - redis:/data
    networks:
      - traefik
    restart: always

  nextcloud:
    image: crazymax/nextcloud:${NEXTCLOUD_TAG}
    container_name: nextcloud
    depends_on:
      - db
      - redis
    volumes:
      - ${MOUNT_DATA}:/data
    networks:
      - traefik
    env_file:
      - secrets.env
    labels:
      - "traefik.enable=true"
      - "traefik.backend=nextcloud"
      - "traefik.nc.port=8000"
      - "traefik.nc.frontend.rule=Host:ptatooine.myqnapcloud.com"
      - "traefik.nc.frontend.redirect.permanent=true"
      - "traefik.nc.frontend.redirect.regex=https://(.*)/.well-known/(card|cal)dav"
      - "traefik.nc.frontend.redirect.replacement=https://$$1/remote.php/dav/"
    restart: always

  cron:
    image: crazymax/nextcloud:${NEXTCLOUD_TAG}
    container_name: nextcloud_cron
    depends_on:
      - nextcloud
    volumes:
      - ${MOUNT_DATA}:/data
    networks:
      - traefik
    env_file:
      - secrets.env
    environment:
      - "SIDECAR_CRON=1"
      - "CRON_PERIOD=*/15 * * * *"
    restart: always

  backup:
    image: blacklabelops/volumerize
    restart: unless-stopped
    volumes:
      - backup_cache:/volumerize-cache
      - db:/source/db
      - data:/source/nextcloud
      - /share/Backup/docker/volumes/nextcloud/db:/backup/db
      - /share/Backup/docker/volumes/nextcloud/nextcloud:/backup/nextcloud
    environment:
      - TZ=Europe/Berlin
      - VOLUMERIZE_SOURCE1=/source/db
      - VOLUMERIZE_TARGET1=file:///backup/db
      - VOLUMERIZE_CACHE1=/volumerize-cache/db
      - VOLUMERIZE_SOURCE2=/source/nextcloud
      - VOLUMERIZE_TARGET2=file:///backup/nextcloud
      - VOLUMERIZE_CACHE2=/volumerize-cache/nextcloud
      - VOLUMERIZE_JOBBER_TIME=0 0 2 * * 0

volumes:
  redis:

networks:
  traefik:
    external:
      name: traefik_default
