networks:
  traefik:
    name: traefik
    external: true

services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    volumes:
      - /share/docker/home-assistant/volumes/config:/config
      - /etc/localtime:/etc/localtime:ro
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.home-assistant.entrypoints=websecure
      - traefik.http.routers.home-assistant.rule=Host(`home.patz.app`)
      - traefik.http.routers.home-assistant.tls=true
      - traefik.http.routers.home-assistant.tls.certresolver=patz.app
      - traefik.http.routers.home-assistant.tls.domains[0].main=patz.app
      - traefik.http.routers.home-assistant.tls.domains[0].sans=home.patz.app
      - traefik.http.services.home-assistant.loadbalancer.server.port=8123

