version: "3.5"

services:
  traefik:
    image: traefik:v2.0-alpine
    container_name: traefik
    ports:
      - 80:80
      - 443:443
    volumes:
      - "./acme.json:/acme.json"
      - "./traefik.toml:/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefik
      - default
    restart: always

  db:
    image: mariadb:10.2
    container_name: nextcloud_db
    volumes:
      - "db:/var/lib/mysql"
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE=nextcloud"
      - "MYSQL_USER=nextcloud"
      - "MYSQL_PASSWORD=asupersecretpassword"
    networks:
      - traefik
    restart: always

  redis:
    image: redis:4.0-alpine
    container_name: nextcloud_redis
    volumes:
      - "redis:/data"
    restart: always

  nextcloud:
    image: crazymax/nextcloud:latest
    container_name: nextcloud
    depends_on:
      - db
      - redis
    volumes:
      - "nextcloud:/data"
    labels:
      traefik.enable: true
      traefik.backend: nextcloud
      traefik.port: 8000
      traefik.http.middlewares.redirect-https.redirectscheme.scheme: "https"
      traefik.http.middlewares.strip-prefix.stripprefix.prefixes: "/nextcloud"
      traefik.http.middlewares.replace-local.redirectregex.regex: "^https://tatooine.local/(.*)"
      traefik.http.middlewares.replace-local.redirectregex.replacement: "https://ptatooine.myqnapcloud.com/$${1}"
      traefik.http.routers.nextcloud.rule: "PathPrefix(`/nextcloud`)"
      traefik.http.routers.nextcloud.entryPoints: "http, https"
      traefik.http.routers.nextcloud.middlewares: "redirect-https, replace-local"
    env_file:
      - "./nextcloud.env"
    networks:
      - traefik
    restart: always

  cron:
    image: crazymax/nextcloud:latest
    container_name: nextcloud_cron
    depends_on:
      - nextcloud
    volumes:
      - "nextcloud:/data"
    env_file:
      - "./nextcloud.env"
    environment:
      - "SIDECAR_CRON=1"
      - "CRON_PERIOD=*/15 * * * *"
    restart: always

volumes:
  db:
  nextcloud:
  redis:

networks:
  traefik:
    name: traefik
  default:

