[global]
  checkNewVersion = true
  sendAnonymousUsage = true

[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.web-secure]
    address = ":443"

[providers]
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    network = "traefik"
    watch = true
    exposedByDefault = false

[acme]
  email = "mailto@martin-patz.de"
  storage = "acme.json"
  onHostRule = true
  [acme.httpChallenge]
    entryPoint = "web"
  [[acme.domains]]
    main = "ptatooine.myqnapcloud.com"

