version: "3"


services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    networks:
      private:
        ipv4_address: 172.31.0.3
    volumes:
      - /mnt/ssd-1tb/docker/pritunl-vpn/db:/data/db
      - db_config:/data/configdb
    labels:
      - traefik.enable=false

  pritunl:
    image: goofball222/pritunl:${PRITUNL_TAG:-latest}
    restart: unless-stopped
    privileged: true
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      private:
        ipv4_address: 172.31.0.2
      traefik:
    links:
      - mongo
    depends_on:
      - mongo
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 1194:1194
      - 1194:1194/udp
    expose:
      - 22
      - 443
      - 2222
      - 9700
    environment:
      - TZ=UTC+2
      - MONGODB_URI=mongodb://mongo:27017/pritunl
      - REVERSE_PROXY=true
      # - WIREGUARD=true
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.vpn.entrypoints=websecure
      - traefik.http.routers.vpn.rule=Host(`vpn.patz.app`)
      - traefik.http.routers.vpn.tls=true
      - traefik.http.routers.vpn.tls.certresolver=patz.app
      - traefik.http.routers.vpn.tls.domains[0].main=patz.app
      - traefik.http.routers.vpn.tls.domains[0].sans=vpn.patz.app
      - traefik.http.routers.vpn.service=vpn
      - traefik.http.services.vpn.loadbalancer.server.port=9700

volumes:
  db:
  db_config:

networks:
  traefik:
    name: traefik
    external: true
  private:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/24
