networks:

  traefik:
    name: traefik
    external: true


services:

  bergaufboardab:
    image: httpd:alpine
    restart: unless-stopped
    volumes:
      - ${REPO_ROOT}/www/bergaufboardab.de:/usr/local/apache2/htdocs/
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bergaufboardab.rule=Host(`bergaufboardab.de`)"
      - "traefik.http.routers.bergaufboardab.entrypoints=websecure"
      - "traefik.http.routers.bergaufboardab.tls.certresolver=bergaufboardab.de"
      - "traefik.http.services.bergaufboardab.loadbalancer.server.port=80"

  patz.family:
    image: httpd:alpine
    restart: unless-stopped
    volumes:
      - ${REPO_ROOT}/www/patz.family:/usr/local/apache2/htdocs/
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.patz-family.rule=Host(`patz.family`)"
      - "traefik.http.routers.patz-family.entrypoints=websecure"
      - "traefik.http.routers.patz-family.tls.certresolver=patz.family"
      - "traefik.http.services.patz-family.loadbalancer.server.port=80"
