http:
  routers:
    traefik-websecure:
      entrypoints: websecure
      rule: "Host(`traefik.patz.app`)"
      middlewares:
        - keycloak@file
      tls:
        certResolver: patz.app
        domains:
          - main: "patz.app"
            sans:
              - "traefik.patz.app"
      service: api@internal

