http:
  routers:
    traefik-websecure:
      entrypoints: websecure
      rule: "Host(`traefik.patz.app`)"
      middlewares:
        - keycloak@file
      tls:
        certResolver: patz.app
      service: api@internal
