http:
  routers:
    traefik-websecure:
      entrypoints: websecure
      rule: "Host(`traefik.patz.app`)"
      middlewares:
        - auth
      tls:
        certResolver: patz.app
        domains:
          - main: "patz.app"
            sans:
              - "traefik.patz.app"
      service: api@internal
  middlewares:
    auth:
      basicAuth:
        usersFile: /etc/traefik/dynamic/api_users_passwords.txt

