http:
  routers:
    traefik-web:
      entrypoints: web
      rule: "Host(`traefik.patz.app`)"
      middlewares:
        - redirect-https
      service: api@internal
    traefik-websecure:
      entrypoints: websecure
      rule: "Host(`traefik.patz.app`)"
      middlewares:
        - auth
      tls:
        certResolver: patz.app
        domains:
          - main: "patz.app"
            sans:
              - "traefik.patz.app"
      service: api@internal
  middlewares:
    redirect-https:
      redirectScheme:
        scheme: https
    auth:
      basicAuth:
        users:
          - "admin:$apr1$3XFrbaba$UjpbdjwdD6ie9eqGcHlou/"

