http:

  routers:

    redirect-https:
      entrypoints:
        - web
      middlewares:
        - redirect-https
      rule: HostRegexp(`{host:.+}`)
      service: noop
    http-catch-all:
      entrypoints:
        - web
        - websecure
      middlewares:
        - redirect-www-to-https
      rule: "HostRegexp(`{host:(www\\.).+}`)"
      service: noop
    nas:
      entrypoints:
        - websecure
      rule: "Host(`nas.patz.app`)"
      middlewares:
        - keycloak
      tls:
        certResolver: patz.app
        domains:
          - main: "patz.app"
            sans:
              - "nas.patz.app"
      service: nas
    home-assistant:
     entrypoints:
       - websecure
     rule: "Host(`home.patz.app`)"
     tls:
       certResolver: patz.app
       domains:
         - main: "patz.app"
           sans:
             - "home.patz.app"
     service: home_assistant

  middlewares:

    redirect-https:
      redirectScheme:
        scheme: https
    redirect-www-to-https:
      redirectRegex:
        regex: "^https?://(?:www\\.)?(.+)"
        replacement: "https://${1}"
        permanent: true
    security-headers:
      headers:
        customResponseHeaders:
          X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex"
          server: ""
        sslProxyHeaders:
          X-Forwarded-Proto: https
        customRequestHeaders:
          X-Forwarded-Proto: https
        referrerPolicy: "same-origin"
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        contentTypeNosniff: true
        browserXssFilter: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 63072000
        stsPreload: true
    keycloak:
      forwardAuth:
        address: "http://forward_auth:4181"
        trustForwardHeader: true
        authResponseHeaders:
          - "X-Forwarded-User"

  services:

    noop:
      loadBalancer:
        servers:
          - url: http://192.168.1.1
    # The host.docker alias depends on the DPS service
    nas:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:81
    home_assistant:
     loadBalancer:
       servers:
         - url: http://192.168.1.3:8123
