http:
  routers:
    redirect-https:
      entrypoints:
        - web
      middlewares:
        - redirect-https
      rule: HostRegexp(`{host:.+}`)
      service: noop
    http-catch-all:
      entrypoints:
        - web
        - websecure
      middlewares:
        - redirect-www-to-https
      rule: "HostRegexp(`{host:(www\\.).+}`)"
      service: noop
    nas:
      entrypoints:
        - websecure
      rule: "Host(`nas.patz.app`)"
      tls:
        certResolver: patz.app
        domains:
          - main: "patz.app"
            sans:
              - "nas.patz.app"
      service: nas
  middlewares:
    redirect-https:
      redirectScheme:
        scheme: https
    redirect-www-to-https:
      redirectRegex:
        regex: "^https?://(?:www\\.)?(.+)"
        replacement: "https://${1}"
        permanent: true
    ssl-header:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: https
    no-follow-header:
      headers:
        customRequestHeaders:
          X-Robots-Tag: "noindex, nofollow"
    keycloak:
      forwardAuth:
        address: "http://forward_auth:4181"
        trustForwardHeader: true
        authResponseHeaders:
          - "X-Forwarded-User"
  services:
    noop:
      loadBalancer:
        servers:
          - url: http://192.168.1.1
    # The host.docker alias depends on the DPS service
    nas:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:81
