http:
  routers:
    redirect-https:
      entrypoints:
        - web
      middlewares:
        - redirect-https
      rule: "HostRegexp(`{host:.+}`)"
      service: "noop"
  middlewares:
    redirect-https:
      redirectScheme:
        scheme: https
    keycloak:
      forwardAuth:
        address: "http://forward-auth:4181"
        trustForwardHeader: true
        authResponseHeaders:
          - "X-Forwarded-User"
  services:
    noop:
      loadBalancer:
        servers:
          - url: http://192.168.1.1

