http:
  routers:
    redirect-https:
      entrypoints:
        - web
      middlewares:
        - redirect-https
      rule: "HostRegexp(`{host:.+}`)"
      service: noop
    nas:
      entrypoints:
        - websecure
      rule: "Host(`nas.patz.app`)"
      tls:
        certResolver: patz.app
        domains:
          - main: "patz.app"
            sans:
              - "nas.patz.app"
      service: nas
  middlewares:
    redirect-https:
      redirectScheme:
        scheme: https
    keycloak:
      forwardAuth:
        address: "http://forward_auth:4181"
        trustForwardHeader: true
        authResponseHeaders:
          - "X-Forwarded-User"
  services:
    noop:
      loadBalancer:
        servers:
          - url: http://192.168.1.1
    nas:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:81
