http:
  routers:
    redirect-https:
      entrypoints:
        - web
      middlewares:
        - redirect-https
      rule: "HostRegexp(`{host:.+}`)"
      service: "noop"
  middlewares:
    redirect-https:
      redirectScheme:
        scheme: https
  services:
    noop:
      loadBalancer:
        servers:
          - url: http://192.168.1.1

