http:

  serversTransports:

    trust-internal-tls:
      insecureSkipVerify: true

  routers:

    redirect-https:
      entrypoints:
        - web
      middlewares:
        - redirect-https
      rule: "HostRegexp(`{host:^(.+)$}`)"
      service: noop
    http-catch-all:
      entrypoints:
        - web
        - websecure
      middlewares:
        - redirect-www-to-https
      rule: "HostRegexp(`{host:^(www\\..+)$}`)"
      service: noop
    nas:
      entrypoints:
        - websecure
      rule: "Host(`nas.arnold.patz.app`)"
      middlewares:
        - keycloak
      tls:
        certResolver: patz.app
      service: nas
    home-assistant:
      entrypoints:
        - websecure
      rule: "Host(`home.patz.app`)"
      tls:
        certResolver: patz.app
      middlewares:
        - keycloak@file
      service: home_assistant
    unifi:
      entrypoints:
        - websecure
      rule: "Host(`wifi.patz.app`)"
      tls:
        certResolver: patz.app
      middlewares:
        - keycloak@file
      service: unifi
    storj1:
      rule: >
        Host(`traefik.storj1.patz.app`)
        || Host(`storj-1tb-1.storj1.patz.app`)
        || Host(`storj-1tb-2.storj1.patz.app`)
        || Host(`storj-2tb-1.storj1.patz.app`)
        || Host(`storj-2tb-2.storj1.patz.app`)
        || Host(`storj-2tb-3.storj1.patz.app`)
        || Host(`storj-3tb-1.storj1.patz.app`)
        || Host(`storj-3tb-2.storj1.patz.app`)
        || Host(`storj-3tb-3.storj1.patz.app`)
        || Host(`storj-3tb-4.storj1.patz.app`)
      entryPoints:
        - websecure
      tls:
        certResolver: patz.app
      middlewares:
        - keycloak@file
      service: storj1-service


  middlewares:

    redirect-https:
      redirectScheme:
        scheme: https
    redirect-www-to-https:
      redirectRegex:
        regex: "^https?://(?:www\\.)?(.+)"
        replacement: "https://${1}"
        permanent: true
    security-headers:
      headers:
        customResponseHeaders:
          X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex"
          server: ""
        sslProxyHeaders:
          X-Forwarded-Proto: https
        customRequestHeaders:
          X-Forwarded-Proto: https
        referrerPolicy: "same-origin"
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        contentTypeNosniff: true
        browserXssFilter: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 63072000
        stsPreload: true
    keycloak:
      forwardAuth:
        address: "http://forward_auth:4181"
        trustForwardHeader: true
        authResponseHeaders:
          - "X-Forwarded-User"

  services:

    noop:
      loadBalancer:
        servers:
          - url: http://192.168.1.1
    # The host.docker alias depends on the DPS service
    nas:
      loadBalancer:
        servers:
          - url: https://host.docker.internal:444
        serversTransport: trust-internal-tls
    home_assistant:
     loadBalancer:
       servers:
         - url: http://192.168.1.3:8123
    storj1-service:
      loadBalancer:
        servers:
          - url: http://192.168.1.5:80
    unifi:
      loadBalancer:
        servers:
          - url: https://192.168.1.3:8443
        serversTransport: trust-internal-tls
