version: '3'

services:

  otrecorder:
    image: owntracks/recorder
    expose:
      - "8083"
    volumes:
      - config:/config
      - store:/store
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.otrecorder.entrypoints=websecure"
      - "traefik.http.routers.otrecorder.rule=Host(`otrecorder.patz.app`)"
      - "traefik.http.routers.otrecorder.tls=true"
      - "traefik.http.routers.otrecorder.tls.certresolver=patz.app"
      - "traefik.http.routers.otrecorder.tls.domains[0].main=patz.app"
      - "traefik.http.routers.otrecorder.tls.domains[0].sans=otrecorder.patz.app"
      - "traefik.http.services.nc.loadbalancer.server.port=8083"
    restart: unless-stopped

  owntracks-frontend:
    image: owntracks/frontend
    expose:
      - "80"
    volumes:
      - ./config.js:/usr/share/nginx/html/config/config.js
    environment:
      - SERVER_HOST=otrecorder
      - SERVER_PORT=8083
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.otfrontend.entrypoints=websecure"
      - "traefik.http.routers.otfrontend.rule=Host(`owntracks.patz.app`)"
      - "traefik.http.routers.otfrontend.tls=true"
      - "traefik.http.routers.otfrontend.tls.certresolver=patz.app"
      - "traefik.http.routers.otfrontend.tls.domains[0].main=patz.app"
      - "traefik.http.routers.otfrontend.tls.domains[0].sans=owntracks.patz.app"
      - "traefik.http.services.nc.loadbalancer.server.port=80"      
    restart: unless-stopped

volumes:
  store:
  config:

networks:
  traefik:
    external:
      name: traefik
