version: '3'

services:

  otrecorder:
    container_name: otrecorder
    image: owntracks/recorder
    expose:
      - "8083"
    volumes:
      - config:/config
      - store:/store
    networks:
      - owntracks
      - traefik
    environment:
      - OTR_USER="recorder"
      - OTR_HOST=mqtt
      - OTR_PORT=1883
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.otrecorder.entrypoints=websecure"
      - "traefik.http.routers.otrecorder.rule=Host(`otrecorder.patz.app`)"
      - "traefik.http.routers.otrecorder.tls=true"
      - "traefik.http.routers.otrecorder.tls.certresolver=patz.app"
      - "traefik.http.routers.otrecorder.tls.domains[0].main=patz.app"
      - "traefik.http.routers.otrecorder.tls.domains[0].sans=otrecorder.patz.app"
      - "traefik.http.services.otrecorder.loadbalancer.server.port=8083"
    restart: unless-stopped

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    expose:
      - "1883"
    volumes:
      - mqtt-auth:/mosquitto/auth
      - mqtt-data:/mosquitto/data
      - mqtt-log:/mosquitto/log
      - ./mosquitto-config:/mosquitto/config
    networks:
      - owntracks
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.otmqtt.entrypoints=websecure"
      - "traefik.http.routers.otmqtt.rule=Host(`otmqtt.patz.app`)"
      - "traefik.http.routers.otmqtt.tls=true"
      - "traefik.http.routers.otmqtt.tls.certresolver=patz.app"
      - "traefik.http.routers.otmqtt.tls.domains[0].main=patz.app"
      - "traefik.http.routers.otmqtt.tls.domains[0].sans=otmqtt.patz.app"
      - "traefik.http.services.otmqtt.loadbalancer.server.port=1883"
    restart: unless-stopped

  owntracks-frontend:
    container_name: otfrontend
    image: owntracks/frontend
    expose:
      - "80"
    volumes:
      - ./config.js:/usr/share/nginx/html/config/config.js
    networks:
      - owntracks
      - traefik
    environment:
      - SERVER_HOST=otrecorder
      - SERVER_PORT=8083
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.otfrontend.entrypoints=websecure"
      - "traefik.http.routers.otfrontend.rule=Host(`owntracks.patz.app`)"
      - "traefik.http.routers.otfrontend.tls=true"
      - "traefik.http.routers.otfrontend.tls.certresolver=patz.app"
      - "traefik.http.routers.otfrontend.tls.domains[0].main=patz.app"
      - "traefik.http.routers.otfrontend.tls.domains[0].sans=owntracks.patz.app"
      - "traefik.http.services.otfrontend.loadbalancer.server.port=80"      
    restart: unless-stopped

volumes:
  store:
  config:
  mqtt-auth:
  mqtt-data:
  mqtt-log:

networks:
  owntracks:
  traefik:
    external:
      name: traefik
