version: '3'

services:

  otrecorder:
    container_name: otrecorder
    image: owntracks/recorder
    expose:
      - "8083"
    volumes:
      - /mnt/ssd-1tb/docker/owntracks/config:/config
      - /mnt/ssd-1tb/docker/owntracks/store:/store
    networks:
      - default
      - traefik
    environment:
      - OTR_USER=
      - OTR_HOST=
      - OTR_PORT=
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.owntracks-recorder-pub.entrypoints=websecure"
      - "traefik.http.routers.owntracks-recorder-pub.rule=Host(`otrecorder.patz.app`) && PathPrefix(`/pub/`)"
      - "traefik.http.routers.owntracks-recorder-pub.tls=true"
      - "traefik.http.routers.owntracks-recorder-pub.tls.certresolver=patz.app"
      - "traefik.http.routers.owntracks-recorder-pub.service=owntracks-recorder"
      - "traefik.http.routers.owntracks-recorder-frontend.entrypoints=websecure"
      - "traefik.http.routers.owntracks-recorder-frontend.rule=Host(`otrecorder.patz.app`)"
      - "traefik.http.routers.owntracks-recorder-frontend.tls=true"
      - "traefik.http.routers.owntracks-recorder-frontend.tls.certresolver=patz.app"
      - "traefik.http.routers.owntracks-recorder-frontend.tls.domains[0].main=patz.app"
      - "traefik.http.routers.owntracks-recorder-frontend.tls.domains[0].sans=otrecorder.patz.app"
      - "traefik.http.routers.owntracks-recorder-frontend.service=owntracks-recorder"
      - "traefik.http.routers.owntracks-recorder-frontend.middlewares=keycloak@file"
      - "traefik.http.services.owntracks-recorder.loadbalancer.server.port=8083"
    restart: unless-stopped

  otfrontend:
    container_name: otfrontend
    image: owntracks/frontend
    expose:
      - "80"
    volumes:
      - ./config.js:/usr/share/nginx/html/config/config.js
    networks:
      - default
      - traefik
    environment:
      - SERVER_HOST=otrecorder
      - SERVER_PORT=8083
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.owntracks-frontend.entrypoints=websecure"
      - "traefik.http.routers.owntracks-frontend.rule=Host(`owntracks.patz.app`)"
      - "traefik.http.routers.owntracks-frontend.tls=true"
      - "traefik.http.routers.owntracks-frontend.tls.certresolver=patz.app"
      - "traefik.http.routers.owntracks-frontend.tls.domains[0].main=patz.app"
      - "traefik.http.routers.owntracks-frontend.tls.domains[0].sans=owntracks.patz.app"
      - "traefik.http.services.owntracks-frontend.loadbalancer.server.port=80"      
      - "traefik.http.routers.owntracks-frontend.middlewares=keycloak@file"
    restart: unless-stopped

networks:
  default:
  traefik:
    external:
      name: traefik
