networks:

  traefik:
    name: traefik
    external: true


services:

  boinc:
    image: boinc/client:${BOINC_TAG}
    container_name: boinc
    restart: unless-stopped
    # network_mode: host
    pid: host
    ports:
      - 1043:1043
      - 31416:31416
    volumes:
      - /mnt/ssd-1tb/docker/boinc:/var/lib/boinc
    networks:
      - traefik
    environment:
      - BOINC_GUI_RPC_PASSWORD=${BOINC_GUI_RPC_PASSWORD}
      - BOINC_CMD_LINE_OPTIONS=--allow_remote_gui_rpc
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.boinc.entrypoints=websecure"
      - "traefik.http.routers.boinc.rule=Host(`boinc.patz.app`)"
      - "traefik.http.routers.boinc.tls=true"
      - "traefik.http.routers.boinc.tls.certresolver=patz.app"
      - "traefik.http.services.boinc.loadbalancer.server.port=80"
