version: "3.3"

services:
  file_browser:
    image: filebrowser/filebrowser:v2.22.1
    restart: always
    volumes:
      - srv:/srv
      - /mnt/hdd-16tb/media:/srv/media
      - /mnt/hdd-16tb/programs:/srv/programs
      - /mnt/hdd-16tb/games:/srv/games
      - /mnt/ssd-1tb/docker/file-browser/db:/database
      - /mnt/ssd-1tb/docker/file-browser/filebrowser.json:/.filebrowser.json
    user: "${PUID}:${PGID}"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.file-browser.rule=Host(`files.patz.app`)"
      - "traefik.http.routers.file-browser.entrypoints=websecure"
      - "traefik.http.routers.file-browser.service=file-browser"
      - "traefik.http.routers.file-browser.tls.certresolver=patz.app"
      - "traefik.http.routers.file-browser.tls.domains[0].main=patz.app"
      - "traefik.http.routers.file-browser.tls.domains[0].sans=files.patz.app"
      - "traefik.http.services.file-browser.loadbalancer.server.port=80"

volumes:
  srv:

networks:
  auth_internal:
    external: true
  traefik:
    external:
      name: traefik



