volumes:
  # unused, mounted to prevent anonymous volumes
  pgdata:


networks:

  auth_internal:
    external: true

  backend:

  traefik:
    name: traefik
    external: true


x-op-restart-policy: &restart_policy
  restart: unless-stopped
x-op-image: &image
  image: openproject/openproject:${OPENPROJECT_TAG:-latest}
x-op-app: &app
  <<: [*image, *restart_policy]
  environment:
    OPENPROJECT_HTTPS: "${OPENPROJECT_HTTPS:-true}"
    OPENPROJECT_HOST__NAME: "openproject.patz.app"
    OPENPROJECT_HSTS: "${OPENPROJECT_HSTS:-true}"
    RAILS_CACHE_STORE: "memcache"
    OPENPROJECT_CACHE__MEMCACHE__SERVER: "cache:11211"
    OPENPROJECT_RAILS__RELATIVE__URL__ROOT: "${OPENPROJECT_RAILS__RELATIVE__URL__ROOT:-}"
    OPENPROJECT_LOG__LEVEL: "${OPENPROJECT_LOG__LEVEL:-warn}"
    DATABASE_URL: "postgres://postgres:p4ssw0rd@db/postgres?pool=20&encoding=unicode&reconnect=true"
    PORT: 8080
    RAILS_MIN_THREADS: 4
    RAILS_MAX_THREADS: 16
    # set to true to enable the email receiving feature. See ./docker/cron for more options
    IMAP_ENABLED: "${IMAP_ENABLED:-false}"
  volumes:
    - /mnt/ssd-1tb/docker/openproject/opdata:/var/openproject/assets
    - pgdata:/var/openproject/pgdata


services:

  db:
    image: postgres:13
    <<: *restart_policy
    stop_grace_period: "3s"
    volumes:
      - /mnt/ssd-1tb/docker/openproject/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: p4ssw0rd
    networks:
      - backend

  cache:
    image: memcached
    <<: *restart_policy
    networks:
      - backend

  web:
    <<: *app
    command: "./docker/prod/web"
    networks:
      - auth_internal
      - backend
      - traefik
    depends_on:
      - db
      - cache
      - seeder
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080${OPENPROJECT_RAILS__RELATIVE__URL__ROOT:-}/health_checks/default"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    labels:
      - autoheal=true
      - "traefik.enable=true"
      - "traefik.http.routers.op.entrypoints=websecure"
      - "traefik.http.routers.op.rule=Host(`openproject.patz.app`)"
      - "traefik.http.routers.op.tls=true"
      - "traefik.http.routers.op.tls.certresolver=patz.app"
      - "traefik.http.services.op.loadbalancer.server.port=8080"

  autoheal:
    image: willfarrell/autoheal:1.2.0
    <<: *restart_policy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      AUTOHEAL_CONTAINER_LABEL: autoheal
      AUTOHEAL_START_PERIOD: 600
      AUTOHEAL_INTERVAL: 30

  worker:
    <<: *app
    command: "./docker/prod/worker"
    networks:
      - backend
    depends_on:
      - db
      - cache
      - seeder

  cron:
    <<: *app
    command: "./docker/prod/cron"
    networks:
      - backend
    depends_on:
      - db
      - cache
      - seeder

  seeder:
    <<: *app
    command: "./docker/prod/seeder"
    restart: on-failure
    networks:
      - backend
