version: "3.2"

services:
  db:
    image: mariadb:10.2
    container_name: nextcloud_db
    volumes:
      - "db:/var/lib/mysql"
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE=nextcloud"
      - "MYSQL_USER=nextcloud"
      - "MYSQL_PASSWORD=asupersecretpassword"
    restart: always

  redis:
    image: redis:4.0-alpine
    container_name: nextcloud_redis
    volumes:
      - "redis:/data"
    ports:
      - 6379:6379
    restart: always

  nextcloud:
    image: nextcloud:fpm
    container_name: nextcloud
    depends_on:
      - db
      - redis
    links:
      - db
    ports:
      - 8000:80
      - 9000:9000
    volumes:
      - "nextcloud:/var/www/html"
    env_file:
      - "./nextcloud.env"
    restart: always

volumes:
  db:
  nextcloud:
  redis:
