volumes:

  lib:


networks:

  default:

  auth_internal:
    external: true

  traefik:
    name: traefik
    external: true


services:

  mariadb:
    image: mariadb:10.8.2
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: mysqld --innodb-buffer-pool-size=128M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    volumes:
      - "/mnt/ssd-1tb/docker/photo-prism/db:/var/lib/mysql"
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: insecure
      MYSQL_DATABASE: photoprism
      MYSQL_USER: photoprism
      MYSQL_PASSWORD: insecure

  photoprism:
    image: photoprism/photoprism:${PHOTOPRISM_TAG:-ubuntu}
    restart: unless-stopped
    depends_on:
      - mariadb
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    networks:
      - auth_internal
      - default
      - traefik
    env_file:
      - .env
    working_dir: "/photoprism"
    volumes:
      - "lib:/var/lib/photoprism"
      - "/mnt/hdd-16tb/docker/photo-prism/storage:/photoprism/storage"
      - "/mnt/hdd-16tb/docker/photo-prism/originals:/photoprism/originals"
      - "/mnt/hdd-16tb/media/plex/PicturesKM:/photoprism/originals/PicturesKM"
      - "/mnt/hdd-16tb/media/plex/Martin:/photoprism/originals/Martin"
      - "/mnt/hdd-16tb/media/plex/Kasandra:/photoprism/originals/Kasandra"
      # - "~/Import:/photoprism/import"                  # *optional* base folder from which files can be imported to originals
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.photo-prism.entrypoints=websecure"
      - "traefik.http.routers.photo-prism.rule=Host(`pictures.patz.app`)"
      - "traefik.http.routers.photo-prism.tls=true"
      - "traefik.http.routers.photo-prism.tls.certresolver=patz.app"
      - "traefik.http.services.photo-prism.loadbalancer.server.port=2342"
