version: '3'

networks:
  auth_internal:
    external: true

services:
  dps:
    image: defreitas/dns-proxy-server
    hostname: dns.mageddo
    expose:
      - 5380
    networks:
      - auth_internal
    volumes:
      - /etc/resolv.conf:/etc/resolv.conf
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=false
    restart: unless-stopped
