networks:
  auth_internal:
    external: true
  traefik:
    name: traefik
    external: true


services:

  dps:
    image: defreitas/dns-proxy-server
    hostname: dns.mageddo
    restart: unless-stopped
    networks:
      - auth_internal
      - traefik
    volumes:
      - /mnt/ssd-1tb/docker/docker-proxy:/app/conf
      - /etc/resolv.conf:/etc/resolv.conf
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=true
      - traefik.http.routers.dps.entrypoints=websecure
      - traefik.http.routers.dps.rule=Host(`proxy.patz.app`)
      - traefik.http.routers.dps.tls=true
      - traefik.http.routers.dps.tls.certresolver=patz.app
      - traefik.http.routers.dps.tls.domains[0].main=patz.app
      - traefik.http.routers.dps.tls.domains[0].sans=proxy.patz.app
      - traefik.http.routers.dps.middlewares=keycloak@file
      - traefik.http.services.dps.loadbalancer.server.port=5380
