version: "3.2"

services:
  patz.app:
    image: linuxserver/ddclient
    env_file:
      - .env
    volumes:
      - ./patz.app:/config
    labels:
      - "traefik.enable=false"
    restart: always
