version: "3.2"

services:
  root:
    image: blaize/docker-dynamic-dns
    env_file:
      - .env
      - secrets-root.env
    environment:
      - HOSTNAME=patz.app
    restart: always
  wildcard:
    image: blaize/docker-dynamic-dns
    env_file:
      - .env
      - secrets-wildcard.env
    environment:
      - HOSTNAME=*.patz.app
    restart: always

