version: "3.7"

networks:
  affine:
  traefik:
    name: traefik
    external: true


services:

  affine:
    image: toeverything/affine-self-hosted:${AFFINE_TAG:-latest}
    restart: always
    env_file: ../stack.env
    networks:
      - traefik
      - affine
    volumes:
      - /mnt/ssd-1tb/docker/affine:/app/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.affine.entrypoints=websecure
      - traefik.http.routers.affine.middlewares=ssl-header@file
      - traefik.http.routers.affine.rule=Host(`affine.patz.app`)
      - traefik.http.routers.affine.tls=true
      - traefik.http.routers.affine.tls.certresolver=patz.app
      - traefik.http.routers.affine.tls.domains[0].main=patz.app
      - traefik.http.routers.affine.tls.domains[0].sans=affine.patz.app
      - traefik.http.services.affine.loadbalancer.server.port=3000
