version: "3.7"


networks:
  traefik:
    name: traefik
    external: true

services:
  wg-easy:
    image: weejewel/wg-easy:${WIREGUARD_TAG:-latest}
    restart: unless-stopped
    volumes:
      - /mnt/ssd-1tb/docker/wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      traefik:
        ipv4_address: 172.21.0.23
    env_file: ../stack.env
    environment:
      - WG_DEVICE=blub
      - WG_HOST=wg.patz.app
      - WG_POST_UP=
        iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth1 -j MASQUERADE;
        iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT;
        iptables -A FORWARD -i wg0 -j ACCEPT;
        iptables -A FORWARD -o wg0 -j ACCEPT;
        iptables -A FORWARD -i eth1 -j ACCEPT;
        iptables -A FORWARD -o eth1 -j ACCEPT;
        # iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE;
    labels:
      - traefik.enable=true
      - traefik.http.routers.wireguard.entrypoints=websecure
      - traefik.http.routers.wireguard.rule=Host(`wg.patz.app`)
      - traefik.http.routers.wireguard.tls.certresolver=patz.app
      - traefik.http.routers.wireguard.tls.domains[0].main=patz.app
      - traefik.http.routers.wireguard.tls.domains[0].sans=wg.patz.app
      - traefik.http.services.wireguard.loadbalancer.server.port=51821
